name: filez
description: "Everytime, Everywhere, Best File Manager"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependency_overrides:
  archive: ^4.0.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  slang: ^4.5.0
  slang_flutter: ^4.5.0
  i18n_extension: ^15.0.4
  
  path_provider: ^2.1.5
  path: ^1.9.1
  cross_file: ^0.3.4+2

  # Database (temp)
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  shared_preferences: ^2.5.2
  flutter_cache_manager: ^3.4.1

  forui: ^0.9.1+1
  responsive_framework: ^1.5.1
  simple_icons: ^14.6.1
  adaptive_theme: ^3.7.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  bloc_concurrency: ^0.3.0

  go_router: ^14.8.1

  mime: ^2.0.0
  http_status: ^3.3.3

  chopper: ^8.1.0
  rhttp: ^0.10.0
  http: ^1.3.0

  dio: ^5.8.0+1
  dio_compatibility_layer: ^0.1.0
  dio_cookie_manager: ^3.2.0

  image: ^4.5.3 # image
  just_audio: ^0.9.46 # Audio
  just_audio_background: ^0.0.1-beta.15
  video_player: ^2.9.3 # Video
  chewie: ^1.10.0
  fvp: ^0.30.0

  # IO Support
  dartssh2: ^2.12.0 # sftp
  ftpconnect: ^2.0.7 # ftp, ftps, ftpes
  tftp: ^1.2.4 # tftp
  minio: ^3.5.7 # s3
  webdav_client: ^1.2.2 # webdav
  smb_connect: ^0.0.9 # smb

  # Editor
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0

  webf: ^0.16.3+1 # html
  archive: ^4.0.4 # zip, tar, gz, xz
  markdown: ^7.3.0 # md
  pdfrx: ^1.1.11 # pdf
  excel: ^4.0.6 # [R/W] xlsx, xls
  docx_file_viewer: ^0.0.7 # docx
  flutter_epub_viewer: ^1.2.1 # epub

  # Quick Metadata
  flutter_video_info: ^1.3.2 # video
  image_size_getter: ^2.4.0 # image
  exif: ^3.3.0 # image exif
  audio_metadata_reader: ^1.1.0 # audio

  # View Better
  syntax_highlight: ^0.4.0

  # Remote Manager
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  shelf_static: ^1.1.3

  share_plus: ^10.1.4
  device_info_plus: ^11.3.3

  flutter_native_splash: ^2.4.5

  # Debug
  talker: ^4.6.14
  talker_flutter: ^4.6.14
  talker_logger: ^4.6.14
  talker_bloc_logger: ^4.6.14
  talker_http_logger: ^0.1.0-dev.40
  talker_rhttp_logger: ^0.0.15
  dart_syslog: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.15

  slang_build_runner: ^4.5.0

  objectbox_generator: ^4.1.0

  shelf_router_generator: ^1.1.1

  chopper_generator: ^8.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
